---
# import numpy
## 1D 2D 3D

In [1]:
import numpy as np # numerical python

---
# 1D

In [2]:

print("1D Arrays")
a = np.array([1,2,3,])
print(a)
print(type(a))

print("Zeros")
c = np.zeros(2)
print(c)

print("Ones")
d = np.ones(5)
print(d)

print("Empty")
e = np.empty(5)
print(len(e)) # length of the array i.e e
print(e)

print("Range elements")
f = np.arange(5)
print(f)

print("spesific range")
g = np.arange(2,20)
print(g)

h = np.arange(2,20,2)# means between 2 - 20 but with difference of 2
print(h)

print("line Spaced Array")
i = np.linspace(0,10,num=5)#num=5 mean there will be 5 numbers between 0 - 10
print(i)


print("Specific data types in array")
j = np.ones(5,dtype=np.int8)
print(j)

k = np.ones(5,dtype=np.float64)
print(k)


price = np.array([10,20,30])
price

price[0] # on index [0] = 10
price.mean()


1D Arrays
[1 2 3]
<class 'numpy.ndarray'>
Zeros
[0. 0.]
Ones
[1. 1. 1. 1. 1.]
Empty
5
[1. 1. 1. 1. 1.]
Range elements
[0 1 2 3 4]
spesific range
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16 18]
line Spaced Array
[ 0.   2.5  5.   7.5 10. ]
Specific data types in array
[1 1 1 1 1]
[1. 1. 1. 1. 1.]


20.0

---
# 2D

In [3]:

print("2D Arrays")

l = np.zeros((2,4))
print(l)
m = np.ones((2,5))
print(m)
n = np.empty((3,4))
print(n)



2D Arrays
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[6.23042070e-307 3.56043053e-307 1.37961641e-306 8.90071135e-308]
 [8.01097889e-307 1.78020169e-306 7.56601165e-307 1.02359984e-306]
 [1.33510679e-306 2.22522597e-306 1.78019082e-306 1.24612285e-306]]


In [4]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [5]:
arr2 = np.array([[5,6],[7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [6]:
# concatenate 
np.concatenate((arr,arr2), axis=0) # 0 for y-axis

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.concatenate((arr,arr2), axis=1) # 1 for x-axis

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

---
# 3D

In [8]:

print("3D Arrays")
o = np.arange(24).reshape(2,3,4)
print(o)

3D Arrays
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [9]:
ar3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
ar3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
ar3d.ndim # to find dimension

3

In [11]:
# to find size of array
ar3d.size

12

In [12]:
# to find shape
ar3d.shape

(3, 2, 2)

In [13]:
#reshape an array
ar3d.reshape(3,4) # as we now size = 12 so we can do something like 3*4 means 3 rows & 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

---
# Array Functions

In [14]:
Array = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
Array
    

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [15]:
# sorting an array
Array.sort()
Array

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [16]:
Array2 = np.array([21.9,32.6,43.6,42.6])
Array2

array([21.9, 32.6, 43.6, 42.6])

In [17]:
# concatenate
Array3 = np.concatenate((Array,Array2))
Array3

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  21.9,  32.6,  43.6,  42.6])

In [18]:
Array3.sort()
Array3

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. ,  21.9,
        32.6,  42.6,  43.6, 100. , 320. ])

---
# Converting    1D - 2D

In [19]:
a = np.array([1,2,3,])
a

array([1, 2, 3])

In [20]:
# row wise conversion
b=a[np.newaxis,:]
b

array([[1, 2, 3]])

In [21]:
# column wise conversion
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3]])

In [22]:
# indexing
a[1:2] # from index [1] - index [2]

array([2])

In [23]:
a.sum() # will sum all numbers

6

In [24]:
a.mean() # will find you mean

2.0

In [25]:
a+6 # will add 6 to each integer

array([7, 8, 9])

In [26]:
a*6 # will multiply 6 to each integer

array([ 6, 12, 18])